---
- name: "update apt packages." # sudo apt update
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required # sudo apt autoremove nodejs npm
  become: yes
  apt:
    autoremove: yes

- name: "install deps." # sudo apt install
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2" # sudo npm install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: extract artifact
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .


- name: start app
  become: yes
  shell:
    npm install
    pm2 stop all  
    pm2 start npm --start  
